### ISSUE TITLE
Iprogress not found

### ISSUE THREAD

**Issue by fredzannarbor** [Palashio/libra#340]
newClient.summarization_query("Please summarize original text")
  |- Preprocessing data...
```
Traceback (most recent call last):

  File "<ipython-input-16-fc357368ba3d>", line 1, in <module>
    newClient.summarization_query("Please summarize original text")

  File "/usr/local/lib/python3.8/site-packages/libra/queries.py", line 961, in summarization_query
    self.models["summarization"] = summarization_query(

  File "/usr/local/lib/python3.8/site-packages/libra/query/nlp_queries.py", line 327, in summarization_query
    tokenizer = T5Tokenizer.from_pretrained("t5-small")

  File "/usr/local/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 911, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 981, in _from_pretrained
    resolved_vocab_files[file_id] = cached_path(

  File "/usr/local/lib/python3.8/site-packages/transformers/file_utils.py", line 253, in cached_path
    output_path = get_from_cache(

  File "/usr/local/lib/python3.8/site-packages/transformers/file_utils.py", line 439, in get_from_cache
    http_get(url, temp_file, proxies=proxies, resume_size=resume_size, user_agent=user_agent)

  File "/usr/local/lib/python3.8/site-packages/transformers/file_utils.py", line 324, in http_get
    progress = tqdm(

  File "/usr/local/lib/python3.8/site-packages/tqdm/notebook.py", line 218, in __init__
    self.container = self.status_printer(

  File "/usr/local/lib/python3.8/site-packages/tqdm/notebook.py", line 96, in status_printer
    raise ImportError(

ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
```

**Comment by anas-awadalla** [comment]
I see. Could you try to run the command below and retrying?

from ipywidgets import IntProgress

If ipywidgets is not found do:

pip install ipywidgets
jupyter nbextension enable --py widgetsnbextension
